### PR TITLE
Fix Build

### PR DESCRIPTION
**Pull request by rhcp011235**

### CODE REVIEW

**Comment by rhcp011235** [comment]
Why was this closed

**Comment by ghost** [comment]
Because it's not needed...the vendorsetup is in vendor/broken....devices
don't even need one...nothing in this is needed

**Comment by rhcp011235** [comment]
The ReadMe for the local manifest is wrong. I corrected it.

**Comment by ghost** [comment]
Then send a pull request for that change....and I'll have the maintainer
look it over...but to add more code to a file that's already not needed was
the reason I closed it....and in all honesty, who reads the
readmes?...lol..but like I say, send one change at a time, and things won't
be closed so fast...

**Comment by rhcp011235** [comment]
Try to be less arrogant. esp when people are trying to help. Fix it yourself. Im out

**Comment by ghost** [comment]
Are you serious?....Arrogant?...All I said was send only shit that really 
needs to be changed....Get over yourself..Bye Nancy

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by CrackerTeg** [comment]
I'm curious why the inherent need to question why a pull request was closed on a project that doesn't belong to you  @rhcp011235. It got closed because it was not needed. Its really that simple.

**Pull request closed without merging**
